### PR TITLE
GitHub Actions support, part 1

### PR DESCRIPTION
**Pull request by pietroalbini**
This PR adds most of the code to support GitHub Actions in RLA, even though it doesn't fully work yet. I plan to open (multiple) followup PRs to fix the bugs uncovered during testing.

r? @Mark-Simulacrum 
cc https://github.com/rust-lang/rust/issues/70890

### CODE REVIEW

**Comment by pietroalbini** [comment]
I'm tracking GHA-related bugs with the [`github-actions`](https://github.com/rust-lang/rust-log-analyzer/labels/github-actions) label.

**Comment by TimNN** [comment]
I haven’t read the entire PR but just for context regarding the “initialize empty index file if not present”: With an untrained index, the results of RLA would be _really_ bad. I think you’d end up attempting to post the _entire_ log as a comment, which I assume GitHub would reject.

**Comment by Mark-Simulacrum** [comment]
Generally seems reasonable -- I don't know that I can review in fine detail (e.g. if the API calls make sense) without putting in a lot of time, and I suspect there's not much point beyond just running it and seeing if it works.

**Comment by pietroalbini** [comment]
> I haven’t read the entire PR but just for context regarding the “initialize empty index file if not present”: With an untrained index, the results of RLA would be really bad. I think you’d end up attempting to post the entire log as a comment, which I assume GitHub would reject.

Great point, I added that during testing (since I didn't have a GHA index file yet). I'll remove the commit.

**Comment by pietroalbini** [comment]
Ok, merging this. I'll open followup PRs.

**Pull request merged**
